# Generated by Django 5.1.5 on 2025-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lost_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='winning_sum',
            field=models.IntegerField(default=0),
        ),
    ]
