# Generated by Django 5.1.5 on 2025-01-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='draw_sum',
            field=models.IntegerField(default=0),
        ),
    ]
