# Generated by Django 5.1.5 on 2025-01-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_draw_sum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'source')},
        ),
    ]
