# Generated by Django 5.1.5 on 2025-01-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('player', 'Player')], default='player', max_length=30),
        ),
    ]
