# Generated by Django 5.1.5 on 2025-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentuserstat',
            name='draws',
            field=models.IntegerField(default=0),
        ),
    ]
