# Generated by Django 5.1.5 on 2025-01-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentuserstat_draws'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentuserstat',
            name='diff_goals',
            field=models.IntegerField(default=0),
        ),
    ]
