# Generated by Django 5.1.5 on 2025-02-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner_point',
            field=models.IntegerField(default=0),
        ),
    ]
