version: "3.8"

services:
  fastapi_app:
    build: ${IMAGE}
    container_name: django_app
    ports:
      - "8001:8000"
    environment:
      TZ: "UTC"
    env_file:
      - .env
    restart: unless-stopped
