# Generated by Django 5.1.5 on 2025-01-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_options_game_is_draw_alter_game_status'),
        ('ratings', '0002_rating_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.game'),
        ),
    ]
