# Generated by Django 5.1.5 on 2025-01-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_options_game_is_draw_alter_game_status'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_games', to='tournament.tournament'),
        ),
    ]
